### ISSUE TITLE
k8s cluster og namespace bør kunne angis samtidig på samme måte

### ISSUE THREAD

**Issue by ahusby** [navikt/deployment-cli#17]
Se https://github.com/navikt/circleci-nais-orb/issues/6#issuecomment-514506181

**Comment by KFBI1706** [comment]
Så bare for å oppsumere vil du ha `--namespace` som et paramter i deployment-cli og `namespace` som et parameter til nais/deploy jobben?

**Comment by ahusby** [comment]
Ja, det vil være en god løsning.

I orb-en brukes navnet "environment" for å angi cluster. Det blir feil, fordi et miljø består av namesapce i tillegg til cluster.

(Navngiving: Jeg ville kanskej kalt det "k8sCluster" og "k8sNamespace", samt "githubRepo", "githubTeam", "githubAppId" og "githubAppPrivateKey", samt "naisMainfestTemplate" og "naisManifestData". For symmetri og mindre implisitt kunnskap nødvendig for den som skal bruke dette.)

**Comment by sillerud** [comment]
Jeg er egentlig litt uenig her. Cluster kreves i payloadet brukt av deployment for å applye Kubernetes ressursen i clusteret. Namespace er en del av nais.yaml(og er miljøspesifikt) og kan da bruke den miljøspesifikke configen man får via --vars. Alle flaggene(bortsett fra version) kreves av deployment for å i det hele tatt kunne gjennomføre en deploy og blir derfor passet inn som et CLI parameter. Versjonen er der fordi det er dynamisk og blir generert av byggjobben.

**Comment by ahusby** [comment]
@TheUnnamedDude Vi mener forskjellig ting med ordet "miljø".

Blir det riktig å oversette det du sier ovenfor til "Namespace er en del av nais.yaml(og er cluster-spesifikt) og kan da bruke den cluster-spesifikke configen man får via --vars.""?

På Slack https://nav-it.slack.com/archives/CL3G3HZ37/p1563957258013100 fant jeg ut at ordet "miljø" kan bety en konfig i Fasit.

**Comment by Kyrremann** [comment]
Denne diskusjonen ble flyttet til [Slack](https://nav-it.slack.com/archives/CL3G3HZ37/p1563957258013100). 

Konklusjonen (?) ble at måten @ahusby ønsker å jobbe støttes ikke av verktøyene våre, og er ikke noe vi ønsker å ytterlig legge til rette for. 
En potensiell løsning (som ikke er lagt ut enda) er å bruke `--var key=value`, hvor man spesifiserer `namespace` som `key`, og hvor du ønsker å treffe som `value`. Dette blir det nærmeste og enkleste vi kan tilby.
