### ISSUE TITLE
Flagget 'ref' har en default-verdi som er en felle

### ISSUE THREAD

**Issue by ahusby** [navikt/deployment-cli#23]
Relatert til https://github.com/navikt/circleci-nais-orb/pull/13

Flagget "ref" har default-verdien "master".  Dette er en skikkelig felle. Foreslår at flagget ikke har noen default, slik at brukeren tvinges til gjøre et bevisst valg her.

Verdien "master" betyr at ved deploy så vil nyeste commit til master-branchen blir deployet. Det er slettes ikke sikkert at det er det brukeren ønsker, faktisk tror jeg det er svært sjelden. Jeg tror en utvikler vanligvis ønsker å deploye den commiten som inneholder de endringene hen selv nettopp har jobbet meg (typisk en merg av en pull-request). Dette er ikke nødvendigvis det samme som nyeste commit i master.

Problemet er dette: En utvikler skal sette opp build&deploy piepline for sitt team. Hen vet ikke helt hva hen holder på med, for dette er jo en type oppgave man gjør sjelden. Utviklingen av løsningen skjer etter metoden prøve-og-feile-til-jeg-finner-et-oppsett-som-ser-ut-til-å-funke. Da vil default (master) fungere i de fleste tilfeller. Utvikleren tenker ikke på disse to scenariene:

1. En annen utvikler kan pushe sin commit til master før du rekker å deploye din commit. Det betyr at du risikerer å deploye noe annet enn du tror du deployer, og hvis den inneholder feil eller uventede endrigner vil forvirringen bli stor
2. Rollback kan enkelt utføres ved å rekjøre det nest nyeste bygget (eller et enda eldre bygg for den sakens skyld). Dette vil _ikke_ funke hvis 'ref'-flagget har verdien master. Da vil man bare redeploye den versjonen somman øsnket å rulle vekk fra. Det vil funke hvis ref har som verdi commitID-en (sha) til den committen som var opphavet til bygget i sin tid.

**Comment by kimtore** [comment]
Flagget `ref` har ingen betydning for hva som blir deployet. Dette styres helt og holdent av hva som ligger i feltet `payload`. Det eneste bruksområdet for `ref` er i Github sin frontend, hvor man  får oversikt over hvilken ref som er deployet i hvilket environment.
