### ISSUE TITLE
go-templates i alerts kræsjer med handlebars

### ISSUE THREAD

**Issue by Kyrremann** [navikt/deployment-cli#25]
Prøver å deploye alerts via deployment-cli/action, men go-templates gjør at Handlebars klager.

```
Error: Failed to render template for file alerts.yaml
Caused by:
Template error: invalid handlebars syntax.
    --> Template error in "Unnamed template":16:24
     |
  13 |       expr: up{app="pt-sak-consumer", job="kubernetes-pods"} == 0
  14 |       for: 2m
  15 |       description: "{{ $labels.app }} er nede i {{ $labels.kubernetes_namespace }}"
     |------------------------^----------------------------------------------------------
  16 |       action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
     |
     = reason: invalid handlebars syntax.
```

Burde ha mulighet til å skru av Handlebars eller en lignende løsning.

**Comment by jhrv** [comment]
`--raw-resource=alerts.yaml` ?
`--no-template-resource=alerts.yaml` ?

**Comment by Kyrremann** [comment]
Ah, det er et felt ja! Skal teste!

**Comment by jhrv** [comment]
Ah, sorry. Kommentaren var ment som løsningsforslag (skrev mens jeg gikk fra toget, så ble noe kortfattet og utydelig)

**Comment by Kyrremann** [comment]
Ah, trodde du mente det var et flagg vi hadde :p

Kunne man ikke også sagt at hvis du ikke bruker flagget `--var` eller `--vars`, så skipper vi handlebars-parsing? For uten de to andre flaggene så blir jo handlebars unødvendig.

**Comment by jhrv** [comment]
Jo, men da fjerner man muligheten for å ha en kombinasjon. F.eks at man vil
template `nais.yaml`, men ikke `alerts.yaml`. Man kunne da kjørt det i to
steg, men da blir historikken rar, i at man får to ulike github deployments
pr kjøring

**Comment by Kyrremann** [comment]
Veldig godt poeng!

**Comment by sillerud** [comment]
Er veldig for å legge til en --raw eller --raw-resource, templating burde ikke være et krav for å bruke deployment-cli. Om man ønsker å gjøre en hybrid med templating og go-templates er dette mulig i dag med endring av [delimiters](https://docs.rs/crate/mustache/0.9.0/source/spec/specs/delimiters.yml). For å ta i bruk delimiters kan man legge inn `{{=[starttag][endtag]=}}` enten først i filen eller før man benytter go-templates, så man kan f.eks. bruke `{{=<??>=}}` for å bytte til `<? version ?>`. Man kan bytte delimiters fler ganger i en fil

**Comment by Kyrremann** [comment]
God idé med `raw-resource`.

Men, enda en ting som hadde vært smooth er om vi ikke sjekket for templating hvis man ikke la til `--var` eller `--vars`? For virker litt snodig at den prøver å template hvis du ikke gir den noe å template med.

**Comment by jhrv** [comment]
deployment-cli tilgjengeliggjør også de andre verdiene den får som template variabler, så det du foreslår vil ikke ha noen effekt med mindre man endrer på den oppførselen. 

Fra doc'en:

> ...deployment-cli will also inject a few values regardless of specifying a config file:
>    
>    ref: git reference. Specified by the --ref flag. Default: master
>    cluster: which cluster the deploy is for. Specified by the --cluster/-c flag. Default: dev-fss
    team: the team this deployment is for. Specified by the --team/t flag.
    version: DEPRECATED, use --var version= instead. The version, this is strictly for templating and should be used to specify which version of the Docker file should be pulled. Specified using the --version flag

**Comment by Kyrremann** [comment]
Ah, det hadde jeg ikke fått med meg 👍
