### ISSUE TITLE
Flytte repo til nais-org

### ISSUE THREAD

**Issue by Kyrremann** [navikt/deployment-cli#26]
Føler denne er knyttet tett opp til NAIS, noen grunn til at denne ikke bør være under nais-org?

**Comment by kimtore** [comment]
Helt enig i at den burde ligge under nais-organisasjonen, men synes ikke det er så viktig å flytte den på dette tidspunktet.

**Comment by Kyrremann** [comment]
Blir løst ved at vi lager nytt cli pga. ny og bedre deploy-pipeline! Se https://github.com/nais/deploy
