### ISSUE TITLE
Kan nais.yml også være JSON?

### ISSUE THREAD

**Issue by ahusby** [navikt/deployment-cli#8]
Den fila som man referer til med flagget --resource, kan det være en JSON-fil eller må det være YAML?

**Comment by jhrv** [comment]
kan være json også

**Comment by sillerud** [comment]
Jeg har vært litt uklar på det, planen er å støtte begge deler, men nå støtter den kun yaml

**Comment by jhrv** [comment]
beklager, leste bare tittelen 😁
Har dere nais manifestet som json @ahusby?

**Comment by ahusby** [comment]
@jhrv  Dette er under utvikling, men ja, fordi jeg brukte curl-kommandoen mot Github API-et, og Github API-et vil ha JSON. Men nå som jeg skal bytte ut curl med deployment-cli kan jeg gå tilbake til YAML.

Uansett burde dokumentasjon og help si hva som gjelder.

**Comment by jhrv** [comment]
Fra README:
`Currently it only supports yaml resource files and json config files.`
+
https://github.com/navikt/deployment-cli/commit/a75f3a7b63c882e6066cc0f7d730b8d2d9725735

Hvis det er behov for JSON lager vi et eget issue på det
