### ISSUE TITLE
Er key en key eller en path

### ISSUE THREAD

**Issue by ahusby** [navikt/deployment-cli#9]
Flaggene --key og --key-base64, skal verdien være selve nøkkelen eller en sti til en fil som inneholder nøkkelen?

**Comment by jhrv** [comment]
https://github.com/navikt/deployment-cli#creating-a-deployment

kan også anbefale #nais-deployment for spørsmål

**Comment by ahusby** [comment]
@jhrv Takk for tips. Jeg ser i eksemplet der noen pseudokonfig som sier "--key=/path/to/private-key.pem". Hovepoenget mitt med å opprette denne issuen er egentlig at dette burde komme tydeligere fram i dokumentasjon og i output fra help-kommandoen. Det burde ikke være nødvendig å spørre på Slack for å få vite dette.

**Comment by ahusby** [comment]
@jhrv Derfor ^ synes jeg denne issue-en bør være åpen inntil doc og help er forbedret.

**Comment by jhrv** [comment]
Det er jeg enig i, men det kom ikke så godt frem på formatet på forespørselen da det var formulert som et spørsmål.

Fikset help: 66fbde9
